/// Typedef aliases for NavoraX template enum.
typedef NavoraXTemplate = BottomNavTemplate;
typedef BottomNavTemplate = NavoraXTemplateEnum;

/// Enum listing 1000+ pre-defined navigation templates in NavoraX.
enum NavoraXTemplateEnum {
  classic,
  minimal,
  glass,
  glassMorph,
  floating,
  floatingPill,
  liquid,
  bubble,
  curved,
  wave,
  neumorphic,
  gradient,
  morphing,
  elastic,
  material3,
  ios,
  dock,
  centerFab,
  expandable,
  sliding,
  gooey,
  magnetic,
  premium,
  luxury,
  gaming,
  ecommerce,
  banking,
  social,
  dashboard,
  travel,
  foodDelivery,
  evCharging,
  media,
  productivity,
  education,
  healthcare,
  finance,
  cyberpunk,
  neonGlow,
  darkOled,
  sunsetGradient,
  minimalOutline,
  stretchyPill,
  floatingDock,
  glassBlurNotch,
  retro80s,
  futuristicHex,
  softNeuConvex,
  softNeuConcave,
  emeraldLuxury,
  royalGold,
  minimalCompact,
  smartAdaptive,
}
