import 'package:flutter/material.dart';
import '../core/navorax_enums.dart';
import '../core/models/navorax_config.dart';
import 'navorax_template.dart';

/// Typedef alias for backward compatibility.
typedef TemplateDefinitions = NavoraXTemplateDefinitions;

/// Reusable generator that produces 1000+ distinct [NavoraXConfig] templates.
class NavoraXTemplateDefinitions {
  static final Map<String, NavoraXConfig> _cache = {};

  /// Handcrafted pre-defined primary template mappings across all [NavoraXTemplateEnum] values.
  static final Map<NavoraXTemplateEnum, NavoraXConfig> primaryTemplates = {
    NavoraXTemplateEnum.classic: const NavoraXConfig(
      id: 'classic',
      name: 'Classic Material',
      category: NavoraXCategory.material3,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.lineTop,
      animation: NavoraXAnimation.fade,
      backgroundColor: Color(0xFF1F1F29),
      activeColor: Color(0xFF6750A4),
      inactiveColor: Color(0xFF8E8E93),
      indicatorColor: Color(0xFF6750A4),
      height: 64,
      elevation: 4,
    ),
    NavoraXTemplateEnum.minimal: const NavoraXConfig(
      id: 'minimal',
      name: 'Minimal Clean',
      category: NavoraXCategory.minimal,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.dot,
      animation: NavoraXAnimation.scale,
      iconStyle: NavoraXIconStyle.standard,
      labelStyle: NavoraXLabelStyle.selectedOnly,
      backgroundStyle: NavoraXBackgroundStyle.solid,
      backgroundColor: Colors.transparent,
      activeColor: Color(0xFF6366F1),
      inactiveColor: Color(0xFF9CA3AF),
      indicatorColor: Color(0xFF6366F1),
      height: 58,
      elevation: 0,
    ),
    NavoraXTemplateEnum.glass: const NavoraXConfig(
      id: 'glass',
      name: 'Frosted Glass',
      category: NavoraXCategory.glassmorphism,
      shape: NavoraXShape.rounded,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.fade,
      backgroundStyle: NavoraXBackgroundStyle.glass,
      backgroundColor: Color(0x30FFFFFF),
      activeColor: Color(0xFF007AFF),
      inactiveColor: Color(0xFF8E8E93),
      indicatorColor: Color(0xFF007AFF),
      borderRadius: BorderRadius.all(Radius.circular(24)),
      margin: EdgeInsets.all(12),
      blurAmount: 16,
      height: 64,
      elevation: 6,
    ),
    NavoraXTemplateEnum.glassMorph: const NavoraXConfig(
      id: 'glass_morph',
      name: 'Ultra Glassmorphic',
      category: NavoraXCategory.glassmorphism,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.pill,
      animation: NavoraXAnimation.elastic,
      backgroundStyle: NavoraXBackgroundStyle.glassMorph,
      backgroundColor: Color(0x4012121E),
      activeColor: Color(0xFF00F2FE),
      inactiveColor: Color(0xFF6C757D),
      indicatorColor: Color(0x2200F2FE),
      borderRadius: BorderRadius.all(Radius.circular(30)),
      margin: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      blurAmount: 24,
      height: 68,
      elevation: 8,
    ),
    NavoraXTemplateEnum.floating: const NavoraXConfig(
      id: 'floating',
      name: 'Floating Capsule',
      category: NavoraXCategory.floating,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.pill,
      animation: NavoraXAnimation.slide,
      backgroundColor: Color(0xFF1E1E2C),
      activeColor: Color(0xFF4E54C8),
      inactiveColor: Color(0xFFA0A5BD),
      indicatorColor: Color(0xFF8F94FB),
      borderRadius: BorderRadius.all(Radius.circular(32)),
      margin: EdgeInsets.symmetric(horizontal: 20, vertical: 14),
      height: 64,
      elevation: 10,
    ),
    NavoraXTemplateEnum.floatingPill: const NavoraXConfig(
      id: 'floating_pill',
      name: 'Stretchy Floating Pill',
      category: NavoraXCategory.pill,
      shape: NavoraXShape.pill,
      indicator: NavoraXIndicator.stretchy,
      animation: NavoraXAnimation.spring,
      backgroundColor: Color(0xFF0F172A),
      activeColor: Color(0xFF38BDF8),
      inactiveColor: Color(0xFF64748B),
      indicatorColor: Color(0xFF0284C7),
      borderRadius: BorderRadius.all(Radius.circular(28)),
      margin: EdgeInsets.symmetric(horizontal: 24, vertical: 16),
      height: 60,
      elevation: 12,
    ),
    NavoraXTemplateEnum.liquid: const NavoraXConfig(
      id: 'liquid',
      name: 'Liquid Teal Flow',
      category: NavoraXCategory.liquid,
      shape: NavoraXShape.liquid,
      indicator: NavoraXIndicator.liquidBubble,
      animation: NavoraXAnimation.liquid,
      backgroundColor: Color(0xFF0D9488),
      activeColor: Colors.white,
      inactiveColor: Color(0xCCCCFBF1),
      indicatorColor: Colors.white,
      height: 66,
      elevation: 6,
    ),
    NavoraXTemplateEnum.bubble: const NavoraXConfig(
      id: 'bubble',
      name: 'Pink Bubble Pop',
      category: NavoraXCategory.bubble,
      shape: NavoraXShape.bubble,
      indicator: NavoraXIndicator.backgroundFill,
      animation: NavoraXAnimation.bounce,
      backgroundColor: Color(0xFFFDF2F8),
      activeColor: Color(0xFFDB2777),
      inactiveColor: Color(0xFF9CA3AF),
      indicatorColor: Color(0xFFFCE7F3),
      borderRadius: BorderRadius.all(Radius.circular(24)),
      height: 64,
      elevation: 2,
    ),
    NavoraXTemplateEnum.curved: const NavoraXConfig(
      id: 'curved',
      name: 'Emerald Curved Top',
      category: NavoraXCategory.curved,
      shape: NavoraXShape.curved,
      indicator: NavoraXIndicator.lineBottom,
      animation: NavoraXAnimation.morph,
      backgroundColor: Color(0xFF1E293B),
      activeColor: Color(0xFF10B981),
      inactiveColor: Color(0xFF64748B),
      indicatorColor: Color(0xFF10B981),
      height: 66,
      elevation: 4,
    ),
    NavoraXTemplateEnum.wave: const NavoraXConfig(
      id: 'wave',
      name: 'Cyan Wave Motion',
      category: NavoraXCategory.curved,
      shape: NavoraXShape.wave,
      indicator: NavoraXIndicator.dot,
      animation: NavoraXAnimation.wave,
      backgroundColor: Color(0xFF0F172A),
      activeColor: Color(0xFF06B6D4),
      inactiveColor: Color(0xFF475569),
      indicatorColor: Color(0xFF22D3EE),
      height: 68,
      elevation: 6,
    ),
    NavoraXTemplateEnum.neumorphic: const NavoraXConfig(
      id: 'neumorphic',
      name: 'Soft Neumorphic Light',
      category: NavoraXCategory.neumorphism,
      shape: NavoraXShape.rounded,
      indicator: NavoraXIndicator.ring,
      animation: NavoraXAnimation.scale,
      backgroundStyle: NavoraXBackgroundStyle.neumorphicConvex,
      backgroundColor: Color(0xFFE0E5EC),
      activeColor: Color(0xFF4D7CFE),
      inactiveColor: Color(0xFFA3B1C6),
      indicatorColor: Color(0xFF4D7CFE),
      borderRadius: BorderRadius.all(Radius.circular(20)),
      margin: EdgeInsets.all(12),
      height: 66,
      elevation: 0,
    ),
    NavoraXTemplateEnum.gradient: const NavoraXConfig(
      id: 'gradient',
      name: 'Sunset Purple Gradient',
      category: NavoraXCategory.gradient,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.fade,
      backgroundStyle: NavoraXBackgroundStyle.gradient,
      gradient: LinearGradient(
        colors: [Color(0xFF8E2DE2), Color(0xFF4A00E0)],
      ),
      activeColor: Colors.white,
      inactiveColor: Color(0xB3FFFFFF),
      indicatorColor: Color(0xFFFFD700),
      borderRadius: BorderRadius.all(Radius.circular(28)),
      margin: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      height: 64,
      elevation: 8,
    ),
    NavoraXTemplateEnum.morphing: const NavoraXConfig(
      id: 'morphing',
      name: 'Morphing Shape Shift',
      category: NavoraXCategory.morphing,
      shape: NavoraXShape.stadium,
      indicator: NavoraXIndicator.pill,
      animation: NavoraXAnimation.morph,
      backgroundColor: Color(0xFF1E1B4B),
      activeColor: Color(0xFFA78BFA),
      inactiveColor: Color(0xFF6B7280),
      indicatorColor: Color(0xFF4C1D95),
      borderRadius: BorderRadius.all(Radius.circular(24)),
      margin: EdgeInsets.all(12),
      height: 64,
      elevation: 6,
    ),
    NavoraXTemplateEnum.elastic: const NavoraXConfig(
      id: 'elastic',
      name: 'Elastic Spring Bounce',
      category: NavoraXCategory.elastic,
      shape: NavoraXShape.pill,
      indicator: NavoraXIndicator.stretchy,
      animation: NavoraXAnimation.elastic,
      backgroundColor: Color(0xFF064E3B),
      activeColor: Color(0xFF34D399),
      inactiveColor: Color(0xFF059669),
      indicatorColor: Color(0xFF34D399),
      borderRadius: BorderRadius.all(Radius.circular(30)),
      margin: EdgeInsets.symmetric(horizontal: 20, vertical: 10),
      height: 62,
      elevation: 8,
    ),
    NavoraXTemplateEnum.material3: const NavoraXConfig(
      id: 'material3',
      name: 'Material 3 Expressive',
      category: NavoraXCategory.material3,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.pill,
      animation: NavoraXAnimation.fade,
      backgroundColor: Color(0xFFF3EDF7),
      activeColor: Color(0xFF1D1B20),
      inactiveColor: Color(0xFF49454F),
      indicatorColor: Color(0xFFE8DEF8),
      height: 72,
      elevation: 0,
    ),
    NavoraXTemplateEnum.ios: const NavoraXConfig(
      id: 'ios',
      name: 'iOS Translucent Tab Bar',
      category: NavoraXCategory.ios,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.none,
      animation: NavoraXAnimation.none,
      backgroundStyle: NavoraXBackgroundStyle.glass,
      backgroundColor: Color(0xCCF9F9F9),
      activeColor: Color(0xFF007AFF),
      inactiveColor: Color(0xFF8E8E93),
      blurAmount: 20,
      height: 56,
      elevation: 0,
    ),
    NavoraXTemplateEnum.dock: const NavoraXConfig(
      id: 'dock',
      name: 'macOS Style Dock',
      category: NavoraXCategory.dock,
      shape: NavoraXShape.dock,
      indicator: NavoraXIndicator.dot,
      animation: NavoraXAnimation.magnetic,
      backgroundStyle: NavoraXBackgroundStyle.glassMorph,
      backgroundColor: Color(0x551E1E2E),
      activeColor: Colors.white,
      inactiveColor: Color(0xFF8888AA),
      indicatorColor: Colors.white,
      borderRadius: BorderRadius.all(Radius.circular(32)),
      margin: EdgeInsets.symmetric(horizontal: 32, vertical: 16),
      blurAmount: 30,
      height: 68,
      elevation: 12,
    ),
    NavoraXTemplateEnum.centerFab: const NavoraXConfig(
      id: 'center_fab',
      name: 'Notched Center FAB',
      category: NavoraXCategory.dock,
      shape: NavoraXShape.notched,
      indicator: NavoraXIndicator.lineTop,
      animation: NavoraXAnimation.slide,
      backgroundColor: Color(0xFF181824),
      activeColor: Color(0xFF6366F1),
      inactiveColor: Color(0xFF64748B),
      indicatorColor: Color(0xFF6366F1),
      height: 64,
      elevation: 8,
    ),
    NavoraXTemplateEnum.expandable: const NavoraXConfig(
      id: 'expandable',
      name: 'Expandable Sliding Bar',
      category: NavoraXCategory.animated,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.pill,
      animation: NavoraXAnimation.expand,
      backgroundColor: Color(0xFF1F2937),
      activeColor: Color(0xFFF59E0B),
      inactiveColor: Color(0xFF9CA3AF),
      indicatorColor: Color(0x33F59E0B),
      borderRadius: BorderRadius.all(Radius.circular(24)),
      margin: EdgeInsets.all(12),
      height: 64,
      elevation: 6,
    ),
    NavoraXTemplateEnum.sliding: const NavoraXConfig(
      id: 'sliding',
      name: 'Sliding Underline Bar',
      category: NavoraXCategory.animated,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.lineBottom,
      animation: NavoraXAnimation.slide,
      backgroundColor: Color(0xFF1E293B),
      activeColor: Color(0xFF38BDF8),
      inactiveColor: Color(0xFF64748B),
      indicatorColor: Color(0xFF38BDF8),
      height: 60,
      elevation: 2,
    ),
    NavoraXTemplateEnum.gooey: const NavoraXConfig(
      id: 'gooey',
      name: 'Gooey Blob Shift',
      category: NavoraXCategory.gooey,
      shape: NavoraXShape.liquid,
      indicator: NavoraXIndicator.liquidBubble,
      animation: NavoraXAnimation.gooey,
      backgroundColor: Color(0xFF4338CA),
      activeColor: Colors.white,
      inactiveColor: Color(0xFFC7D2FE),
      indicatorColor: Colors.white,
      height: 66,
      elevation: 6,
    ),
    NavoraXTemplateEnum.magnetic: const NavoraXConfig(
      id: 'magnetic',
      name: 'Magnetic Physics Pill',
      category: NavoraXCategory.magnetic,
      shape: NavoraXShape.pill,
      indicator: NavoraXIndicator.ring,
      animation: NavoraXAnimation.magnetic,
      backgroundColor: Color(0xFF0F172A),
      activeColor: Color(0xFFF43F5E),
      inactiveColor: Color(0xFF64748B),
      indicatorColor: Color(0xFFF43F5E),
      borderRadius: BorderRadius.all(Radius.circular(28)),
      margin: EdgeInsets.all(14),
      height: 64,
      elevation: 10,
    ),
    NavoraXTemplateEnum.premium: const NavoraXConfig(
      id: 'premium',
      name: 'Platinum Slate Premium',
      category: NavoraXCategory.premium,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.scale,
      backgroundColor: Color(0xFF1E293B),
      activeColor: Color(0xFF38BDF8),
      inactiveColor: Color(0xFF94A3B8),
      indicatorColor: Color(0xFF38BDF8),
      borderRadius: BorderRadius.all(Radius.circular(24)),
      margin: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      height: 64,
      elevation: 10,
    ),
    NavoraXTemplateEnum.luxury: const NavoraXConfig(
      id: 'luxury',
      name: 'Onyx Gold Luxury',
      category: NavoraXCategory.luxury,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.ring,
      animation: NavoraXAnimation.scale,
      backgroundStyle: NavoraXBackgroundStyle.gradient,
      gradient: LinearGradient(
        colors: [Color(0xFF121212), Color(0xFF242424)],
      ),
      activeColor: Color(0xFFFFD700),
      inactiveColor: Color(0xFF777777),
      indicatorColor: Color(0xFFFFD700),
      borderRadius: BorderRadius.all(Radius.circular(24)),
      margin: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      height: 64,
      elevation: 12,
    ),
    NavoraXTemplateEnum.gaming: const NavoraXConfig(
      id: 'gaming',
      name: 'Gaming Cyber Neon',
      category: NavoraXCategory.gaming,
      shape: NavoraXShape.asymmetric,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.pulse,
      backgroundColor: Color(0xFF09090E),
      activeColor: Color(0xFFFF0055),
      inactiveColor: Color(0xFF00F0FF),
      indicatorColor: Color(0xFFFF0055),
      border: Border.fromBorderSide(
        BorderSide(color: Color(0xFF00F0FF), width: 1.5),
      ),
      height: 66,
      elevation: 10,
    ),
    NavoraXTemplateEnum.ecommerce: const NavoraXConfig(
      id: 'ecommerce',
      name: 'E-Commerce Shopping Cart',
      category: NavoraXCategory.ecommerce,
      shape: NavoraXShape.rounded,
      indicator: NavoraXIndicator.pill,
      animation: NavoraXAnimation.bounce,
      backgroundColor: Color(0xFFFFFFFF),
      activeColor: Color(0xFF4F46E5),
      inactiveColor: Color(0xFF9CA3AF),
      indicatorColor: Color(0xFFEEF2FF),
      borderRadius: BorderRadius.all(Radius.circular(20)),
      margin: EdgeInsets.all(10),
      height: 64,
      elevation: 4,
    ),
    NavoraXTemplateEnum.banking: const NavoraXConfig(
      id: 'banking',
      name: 'Sapphire Trust Banking',
      category: NavoraXCategory.banking,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.lineTop,
      animation: NavoraXAnimation.fade,
      backgroundColor: Color(0xFF0A192F),
      activeColor: Color(0xFF64FFDA),
      inactiveColor: Color(0xFF8892B0),
      indicatorColor: Color(0xFF64FFDA),
      height: 64,
      elevation: 6,
    ),
    NavoraXTemplateEnum.social: const NavoraXConfig(
      id: 'social',
      name: 'Social Media Feed',
      category: NavoraXCategory.socialMedia,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.dot,
      animation: NavoraXAnimation.scale,
      backgroundColor: Color(0xFF000000),
      activeColor: Color(0xFFE1306C),
      inactiveColor: Color(0xFF8E8E93),
      indicatorColor: Color(0xFFE1306C),
      height: 58,
      elevation: 0,
    ),
    NavoraXTemplateEnum.dashboard: const NavoraXConfig(
      id: 'dashboard',
      name: 'Analytics Dashboard',
      category: NavoraXCategory.dashboard,
      shape: NavoraXShape.rounded,
      indicator: NavoraXIndicator.pill,
      animation: NavoraXAnimation.slide,
      backgroundColor: Color(0xFF1E293B),
      activeColor: Color(0xFF10B981),
      inactiveColor: Color(0xFF64748B),
      indicatorColor: Color(0x2210B981),
      borderRadius: BorderRadius.all(Radius.circular(16)),
      margin: EdgeInsets.all(12),
      height: 64,
      elevation: 4,
    ),
    NavoraXTemplateEnum.travel: const NavoraXConfig(
      id: 'travel',
      name: 'Ocean Travel & Booking',
      category: NavoraXCategory.travel,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.spring,
      backgroundStyle: NavoraXBackgroundStyle.gradient,
      gradient: LinearGradient(
        colors: [Color(0xFF00B4DB), Color(0xFF0083B0)],
      ),
      activeColor: Colors.white,
      inactiveColor: Color(0xB3FFFFFF),
      indicatorColor: Colors.white,
      borderRadius: BorderRadius.all(Radius.circular(28)),
      margin: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      height: 64,
      elevation: 8,
    ),
    NavoraXTemplateEnum.foodDelivery: const NavoraXConfig(
      id: 'food_delivery',
      name: 'Yummy Food Delivery',
      category: NavoraXCategory.foodDelivery,
      shape: NavoraXShape.pill,
      indicator: NavoraXIndicator.pill,
      animation: NavoraXAnimation.bounce,
      backgroundColor: Color(0xFFFFF7ED),
      activeColor: Color(0xFFEA580C),
      inactiveColor: Color(0xFF9CA3AF),
      indicatorColor: Color(0xFFFFEDD5),
      borderRadius: BorderRadius.all(Radius.circular(28)),
      margin: EdgeInsets.all(12),
      height: 62,
      elevation: 4,
    ),
    NavoraXTemplateEnum.evCharging: const NavoraXConfig(
      id: 'ev_charging',
      name: 'Electric EV Charging',
      category: NavoraXCategory.evCharging,
      shape: NavoraXShape.capsule,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.pulse,
      backgroundColor: Color(0xFF0F172A),
      activeColor: Color(0xFF84CC16),
      inactiveColor: Color(0xFF475569),
      indicatorColor: Color(0xFF84CC16),
      borderRadius: BorderRadius.all(Radius.circular(30)),
      margin: EdgeInsets.all(12),
      height: 64,
      elevation: 8,
    ),
    NavoraXTemplateEnum.media: const NavoraXConfig(
      id: 'media',
      name: 'Cinema & Media Player',
      category: NavoraXCategory.media,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.lineTop,
      animation: NavoraXAnimation.fade,
      backgroundColor: Color(0xFF050505),
      activeColor: Color(0xFFE50914),
      inactiveColor: Color(0xFF737373),
      indicatorColor: Color(0xFFE50914),
      height: 60,
      elevation: 8,
    ),
    NavoraXTemplateEnum.productivity: const NavoraXConfig(
      id: 'productivity',
      name: 'Workspace Productivity',
      category: NavoraXCategory.productivity,
      shape: NavoraXShape.rounded,
      indicator: NavoraXIndicator.lineBottom,
      animation: NavoraXAnimation.slide,
      backgroundColor: Color(0xFF1E1E2D),
      activeColor: Color(0xFF2563EB),
      inactiveColor: Color(0xFF6B7280),
      indicatorColor: Color(0xFF2563EB),
      borderRadius: BorderRadius.all(Radius.circular(16)),
      margin: EdgeInsets.all(10),
      height: 62,
      elevation: 4,
    ),
    NavoraXTemplateEnum.education: const NavoraXConfig(
      id: 'education',
      name: 'Knowledge & E-Learning',
      category: NavoraXCategory.education,
      shape: NavoraXShape.pill,
      indicator: NavoraXIndicator.backgroundFill,
      animation: NavoraXAnimation.scale,
      backgroundColor: Color(0xFFF0FDF4),
      activeColor: Color(0xFF16A34A),
      inactiveColor: Color(0xFF9CA3AF),
      indicatorColor: Color(0xFFDCFCE7),
      borderRadius: BorderRadius.all(Radius.circular(24)),
      margin: EdgeInsets.all(12),
      height: 62,
      elevation: 2,
    ),
    NavoraXTemplateEnum.healthcare: const NavoraXConfig(
      id: 'healthcare',
      name: 'Medical & Healthcare',
      category: NavoraXCategory.healthcare,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.dot,
      animation: NavoraXAnimation.fade,
      backgroundColor: Color(0xFFF0FDFA),
      activeColor: Color(0xFF0D9488),
      inactiveColor: Color(0xFF9CA3AF),
      indicatorColor: Color(0xFF0D9488),
      borderRadius: BorderRadius.all(Radius.circular(24)),
      margin: EdgeInsets.all(12),
      height: 64,
      elevation: 4,
    ),
    NavoraXTemplateEnum.finance: const NavoraXConfig(
      id: 'finance',
      name: 'FinTech Green Emerald',
      category: NavoraXCategory.finance,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.lineTop,
      animation: NavoraXAnimation.slide,
      backgroundColor: Color(0xFF022C22),
      activeColor: Color(0xFF34D399),
      inactiveColor: Color(0xFF059669),
      indicatorColor: Color(0xFF34D399),
      height: 64,
      elevation: 6,
    ),
    NavoraXTemplateEnum.cyberpunk: const NavoraXConfig(
      id: 'cyberpunk',
      name: 'Cyberpunk Neon',
      category: NavoraXCategory.gaming,
      shape: NavoraXShape.asymmetric,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.pulse,
      backgroundColor: Color(0xFF05050A),
      activeColor: Color(0xFFFF0055),
      inactiveColor: Color(0xFF00F0FF),
      indicatorColor: Color(0xFFFF0055),
      border: Border.fromBorderSide(
        BorderSide(color: Color(0xFF00F0FF), width: 1.5),
      ),
      height: 66,
      elevation: 10,
    ),
    NavoraXTemplateEnum.neonGlow: const NavoraXConfig(
      id: 'neon_glow',
      name: 'Neon Cyan Glow',
      category: NavoraXCategory.gaming,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.pulse,
      backgroundColor: Color(0xFF0B0F19),
      activeColor: Color(0xFF00F0FF),
      inactiveColor: Color(0xFF475569),
      indicatorColor: Color(0xFF00F0FF),
      borderRadius: BorderRadius.all(Radius.circular(28)),
      margin: EdgeInsets.all(12),
      height: 66,
      elevation: 10,
    ),
    NavoraXTemplateEnum.darkOled: const NavoraXConfig(
      id: 'dark_oled',
      name: 'True OLED Pitch Black',
      category: NavoraXCategory.modern,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.lineTop,
      animation: NavoraXAnimation.fade,
      backgroundColor: Color(0xFF000000),
      activeColor: Color(0xFFFFD700),
      inactiveColor: Color(0xFF666666),
      indicatorColor: Color(0xFFFFD700),
      height: 64,
      elevation: 0,
    ),
    NavoraXTemplateEnum.sunsetGradient: const NavoraXConfig(
      id: 'sunset_gradient',
      name: 'Sunset Orange & Coral',
      category: NavoraXCategory.gradient,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.slide,
      backgroundStyle: NavoraXBackgroundStyle.gradient,
      gradient: LinearGradient(
        colors: [Color(0xFFFF512F), Color(0xFFDD2476)],
      ),
      activeColor: Colors.white,
      inactiveColor: Color(0xB3FFFFFF),
      indicatorColor: Colors.white,
      borderRadius: BorderRadius.all(Radius.circular(28)),
      margin: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      height: 64,
      elevation: 8,
    ),
    NavoraXTemplateEnum.minimalOutline: const NavoraXConfig(
      id: 'minimal_outline',
      name: 'Minimal Outlined Border',
      category: NavoraXCategory.minimal,
      shape: NavoraXShape.rounded,
      indicator: NavoraXIndicator.dot,
      animation: NavoraXAnimation.scale,
      backgroundColor: Color(0xFFFFFFFF),
      activeColor: Color(0xFF0F172A),
      inactiveColor: Color(0xFF94A3B8),
      indicatorColor: Color(0xFF0F172A),
      border: Border.fromBorderSide(
        BorderSide(color: Color(0xFFE2E8F0), width: 1.5),
      ),
      borderRadius: BorderRadius.all(Radius.circular(20)),
      margin: EdgeInsets.all(12),
      height: 60,
      elevation: 0,
    ),
    NavoraXTemplateEnum.stretchyPill: const NavoraXConfig(
      id: 'stretchy_pill',
      name: 'Stretchy Elastic Pill',
      category: NavoraXCategory.pill,
      shape: NavoraXShape.pill,
      indicator: NavoraXIndicator.stretchy,
      animation: NavoraXAnimation.spring,
      backgroundColor: Color(0xFF0F172A),
      activeColor: Color(0xFF38BDF8),
      inactiveColor: Color(0xFF64748B),
      indicatorColor: Color(0xFF0284C7),
      borderRadius: BorderRadius.all(Radius.circular(28)),
      margin: EdgeInsets.symmetric(horizontal: 24, vertical: 16),
      height: 60,
      elevation: 12,
    ),
    NavoraXTemplateEnum.floatingDock: const NavoraXConfig(
      id: 'floating_dock',
      name: 'macOS Glass Dock Floating',
      category: NavoraXCategory.dock,
      shape: NavoraXShape.dock,
      indicator: NavoraXIndicator.dot,
      animation: NavoraXAnimation.magnetic,
      backgroundStyle: NavoraXBackgroundStyle.glassMorph,
      backgroundColor: Color(0x551E1E2E),
      activeColor: Colors.white,
      inactiveColor: Color(0xFF8888AA),
      indicatorColor: Colors.white,
      borderRadius: BorderRadius.all(Radius.circular(32)),
      margin: EdgeInsets.symmetric(horizontal: 28, vertical: 14),
      blurAmount: 24,
      height: 66,
      elevation: 10,
    ),
    NavoraXTemplateEnum.glassBlurNotch: const NavoraXConfig(
      id: 'glass_blur_notch',
      name: 'Notched Glass Blur',
      category: NavoraXCategory.glassmorphism,
      shape: NavoraXShape.notched,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.fade,
      backgroundStyle: NavoraXBackgroundStyle.glassMorph,
      backgroundColor: Color(0x4012121E),
      activeColor: Color(0xFF00F2FE),
      inactiveColor: Color(0xFF6C757D),
      indicatorColor: Color(0xFF00F2FE),
      blurAmount: 20,
      height: 64,
      elevation: 8,
    ),
    NavoraXTemplateEnum.retro80s: const NavoraXConfig(
      id: 'retro_80s',
      name: 'Retro 80s Synthwave',
      category: NavoraXCategory.gaming,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.lineBottom,
      animation: NavoraXAnimation.bounce,
      backgroundStyle: NavoraXBackgroundStyle.gradient,
      gradient: LinearGradient(
        colors: [Color(0xFF240046), Color(0xFF3C096C)],
      ),
      activeColor: Color(0xFFFF9E00),
      inactiveColor: Color(0xFFC77DFF),
      indicatorColor: Color(0xFFFF9E00),
      height: 64,
      elevation: 8,
    ),
    NavoraXTemplateEnum.futuristicHex: const NavoraXConfig(
      id: 'futuristic_hex',
      name: 'Futuristic Hexagon',
      category: NavoraXCategory.gaming,
      shape: NavoraXShape.hexagon,
      indicator: NavoraXIndicator.glow,
      animation: NavoraXAnimation.pulse,
      backgroundColor: Color(0xFF0A0E17),
      activeColor: Color(0xFF00FFCC),
      inactiveColor: Color(0xFF334155),
      indicatorColor: Color(0xFF00FFCC),
      height: 68,
      elevation: 10,
    ),
    NavoraXTemplateEnum.softNeuConvex: const NavoraXConfig(
      id: 'soft_neu_convex',
      name: 'Soft Neumorphic Convex',
      category: NavoraXCategory.neumorphism,
      shape: NavoraXShape.rounded,
      indicator: NavoraXIndicator.ring,
      animation: NavoraXAnimation.scale,
      backgroundStyle: NavoraXBackgroundStyle.neumorphicConvex,
      backgroundColor: Color(0xFFE0E5EC),
      activeColor: Color(0xFF3B82F6),
      inactiveColor: Color(0xFFA3B1C6),
      indicatorColor: Color(0xFF3B82F6),
      borderRadius: BorderRadius.all(Radius.circular(20)),
      margin: EdgeInsets.all(12),
      height: 66,
      elevation: 0,
    ),
    NavoraXTemplateEnum.softNeuConcave: const NavoraXConfig(
      id: 'soft_neu_concave',
      name: 'Soft Neumorphic Concave',
      category: NavoraXCategory.neumorphism,
      shape: NavoraXShape.rounded,
      indicator: NavoraXIndicator.pill,
      animation: NavoraXAnimation.fade,
      backgroundStyle: NavoraXBackgroundStyle.neumorphicConcave,
      backgroundColor: Color(0xFF1E293B),
      activeColor: Color(0xFF38BDF8),
      inactiveColor: Color(0xFF64748B),
      indicatorColor: Color(0x3338BDF8),
      borderRadius: BorderRadius.all(Radius.circular(20)),
      margin: EdgeInsets.all(12),
      height: 66,
      elevation: 0,
    ),
    NavoraXTemplateEnum.emeraldLuxury: const NavoraXConfig(
      id: 'emerald_luxury',
      name: 'Emerald & Gold Luxury',
      category: NavoraXCategory.luxury,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.ring,
      animation: NavoraXAnimation.scale,
      backgroundStyle: NavoraXBackgroundStyle.gradient,
      gradient: LinearGradient(
        colors: [Color(0xFF064E3B), Color(0xFF022C22)],
      ),
      activeColor: Color(0xFFFFD700),
      inactiveColor: Color(0xFF6EE7B7),
      indicatorColor: Color(0xFFFFD700),
      borderRadius: BorderRadius.all(Radius.circular(24)),
      margin: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      height: 64,
      elevation: 12,
    ),
    NavoraXTemplateEnum.royalGold: const NavoraXConfig(
      id: 'royal_gold',
      name: 'Luxury Royal Gold',
      category: NavoraXCategory.luxury,
      shape: NavoraXShape.floating,
      indicator: NavoraXIndicator.ring,
      animation: NavoraXAnimation.scale,
      backgroundStyle: NavoraXBackgroundStyle.gradient,
      gradient: LinearGradient(
        colors: [Color(0xFF1A1A1A), Color(0xFF2C2C2C)],
      ),
      activeColor: Color(0xFFFFD700),
      inactiveColor: Color(0xFF888888),
      indicatorColor: Color(0xFFFFD700),
      borderRadius: BorderRadius.all(Radius.circular(24)),
      margin: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      height: 64,
      elevation: 12,
    ),
    NavoraXTemplateEnum.minimalCompact: const NavoraXConfig(
      id: 'minimal_compact',
      name: 'Ultra Compact Bar',
      category: NavoraXCategory.minimal,
      shape: NavoraXShape.flat,
      indicator: NavoraXIndicator.dot,
      animation: NavoraXAnimation.fade,
      labelStyle: NavoraXLabelStyle.neverShow,
      backgroundColor: Color(0xFF0F172A),
      activeColor: Color(0xFF38BDF8),
      inactiveColor: Color(0xFF475569),
      indicatorColor: Color(0xFF38BDF8),
      height: 52,
      elevation: 0,
    ),
    NavoraXTemplateEnum.smartAdaptive: const NavoraXConfig(
      id: 'smart_adaptive',
      name: 'Smart Adaptive System',
      category: NavoraXCategory.modern,
      shape: NavoraXShape.pill,
      indicator: NavoraXIndicator.pill,
      animation: NavoraXAnimation.elastic,
      backgroundColor: Color(0xFF0F172A),
      activeColor: Color(0xFF38BDF8),
      inactiveColor: Color(0xFF94A3B8),
      indicatorColor: Color(0x3338BDF8),
      borderRadius: BorderRadius.all(Radius.circular(30)),
      margin: EdgeInsets.all(12),
      height: 64,
      elevation: 6,
    ),
  };

  /// Retrieves or builds a configuration for any template ID (0 to 1000+).
  static NavoraXConfig getConfigForId(String id) {
    if (_cache.containsKey(id)) {
      return _cache[id]!;
    }

    for (final entry in primaryTemplates.entries) {
      if (entry.value.id == id || entry.key.name == id) {
        return entry.value;
      }
    }

    final config = _generateSyntheticConfig(id);
    _cache[id] = config;
    return config;
  }

  /// Generates 1000+ unique visual template configurations programmatically.
  static NavoraXConfig _generateSyntheticConfig(String id) {
    final hash = id.hashCode.abs();

    const categories = NavoraXCategory.values;
    final category = categories[hash % categories.length];

    const shapes = NavoraXShape.values;
    final shape = shapes[(hash ~/ 3) % shapes.length];

    const indicators = NavoraXIndicator.values;
    final indicator = indicators[(hash ~/ 7) % indicators.length];

    const animations = NavoraXAnimation.values;
    final animation = animations[(hash ~/ 11) % animations.length];

    const bgStyles = NavoraXBackgroundStyle.values;
    final bgStyle = bgStyles[(hash ~/ 13) % bgStyles.length];

    const colorPalettes = [
      [Color(0xFF0F172A), Color(0xFF38BDF8), Color(0xFF64748B)],
      [Color(0xFF1E1E2C), Color(0xFF8F94FB), Color(0xFFA0A5BD)],
      [Color(0xFF111827), Color(0xFF10B981), Color(0xFF6B7280)],
      [Color(0xFF000000), Color(0xFFFF0055), Color(0xFF00F0FF)],
      [Color(0xFF2C3E50), Color(0xFFE74C3C), Color(0xFFBDC3C7)],
      [Color(0xFF1A1A2E), Color(0xFFE94560), Color(0xFF16213E)],
      [Color(0xFF064E3B), Color(0xFF34D399), Color(0xFFA7F3D0)],
      [Color(0xFF4C1D95), Color(0xFFA78BFA), Color(0xFFDDD6FE)],
      [Color(0xFF831843), Color(0xFFF472B6), Color(0xFFFBCFE8)],
      [Color(0xFF7C2D12), Color(0xFFFB923C), Color(0xFFFFEDD5)],
    ];

    final palette = colorPalettes[(hash ~/ 17) % colorPalettes.length];
    final borderRadius = (hash % 2 == 0)
        ? BorderRadius.circular(((hash % 30) + 8).toDouble())
        : BorderRadius.zero;

    final margin = (shape == NavoraXShape.floating || shape == NavoraXShape.pill)
        ? EdgeInsets.symmetric(
            horizontal: ((hash % 16) + 12).toDouble(),
            vertical: ((hash % 10) + 8).toDouble(),
          )
        : EdgeInsets.zero;

    return NavoraXConfig(
      id: id,
      name: '${category.name.toUpperCase()} Template #${(hash % 999) + 1}',
      category: category,
      shape: shape,
      indicator: indicator,
      animation: animation,
      backgroundStyle: bgStyle,
      backgroundColor: palette[0],
      activeColor: palette[1],
      inactiveColor: palette[2],
      indicatorColor: palette[1],
      borderRadius: borderRadius,
      margin: margin,
      height: 56.0 + (hash % 20),
      elevation: ((hash % 12) + 2).toDouble(),
      blurAmount: bgStyle == NavoraXBackgroundStyle.glass ? 16.0 : 0.0,
    );
  }
}
